/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: platform:/resource/test/src/ScrewFastening.lf
 */

#include "reactor-cpp/reactor-cpp.hh"

#include "ScrewFastening/_lf_preamble.hh"

using namespace std::chrono_literals;
using namespace reactor::operators;

            
