/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: platform:/resource/test/src/HelloWorld.lf
 */

#include "HelloWorld/A.hh"

using namespace reactor::operators;

  // private preamble

// outer constructor
A::A(const std::string& name, reactor::Environment* __lf_environment, Parameters&& __lf_parameters)
  : reactor::Reactor(name, __lf_environment)
  , __lf_inner(this, std::forward<Parameters>(__lf_parameters))
  //reactor instances
  // timers
  // actions
  
            
  // reaction views
  
  
{
            
            
  // reaction views
  
  
}
A::A(const std::string& name, reactor::Reactor* __lf_container, Parameters&& __lf_parameters)
  : reactor::Reactor(name, __lf_container)
  , __lf_inner(this, std::forward<Parameters>(__lf_parameters))
  //reactor instances
  // timers
  // actions
  
            
  // reaction views
  
  
{
            
            
  // reaction views
  
  
}

// inner constructor
A::Inner::Inner(::reactor::Reactor* reactor, Parameters&& __lf_parameters)
  : LFScope(reactor)
  , Parameters(std::forward<Parameters>(__lf_parameters))
  // state variables
{}

void A::assemble() {
  // r0
  r0.declare_trigger(&x);
          
  r0.declare_antidependency(&y);
          
  
  // r1
  r1.declare_trigger(&x);
  r1.declare_trigger(&z);
          
  r1.declare_antidependency(&y);
  // connections
}

// methods


// reaction reaction_1

void A::Inner::r0_body(
  [[maybe_unused]] const reactor::Input<int>& x,
  reactor::Output<int>& y)  {
  cout<<"receive at A"<<endl;
  // ... something here ...
}

// reaction reaction_2

void A::Inner::r1_body(
  [[maybe_unused]] const reactor::Input<int>& x,
  [[maybe_unused]] const reactor::Input<int>& z,
  reactor::Output<int>& y)  {
  cout<<"receive at x,z"<<endl;
  // ... something here ...
}

        
