/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: platform:/resource/test/src/HelloWorld.lf
 */
 
#pragma once

#include "reactor-cpp/reactor-cpp.hh"
#include "lfutil.hh"

using namespace std::chrono_literals;

#include "HelloWorld/_lf_preamble.hh"

        

// public preamble


class receiver: public reactor::Reactor {
public:
  struct Parameters {
    using __lf_period_t = reactor::Duration;
    const __lf_period_t period = __lf_period_t(30ms);
  };

 private:
        

  class Inner: public lfutil::LFScope, public Parameters {
    using Parameters::period;
    // state variable
    
    // methods
    
    // reaction bodies
    void r0_body(
      [[maybe_unused]] const reactor::StartupTrigger& startup,
      reactor::LogicalAction<void>& ready); 
    void r1_body([[maybe_unused]] const reactor::Input<double>& ia);
    // deadline handlers
    

    Inner(reactor::Reactor* reactor, Parameters&& parameters);

   friend receiver;
  };

  Inner __lf_inner;

  const typename Parameters::__lf_period_t& period = __lf_inner.period;
  // reactor instances
  // timers
  
  // actions
  reactor::LogicalAction<void> ready;
  reactor::LogicalAction<void> interval;
  // default actions
  reactor::StartupTrigger startup {"startup", this};
  reactor::ShutdownTrigger shutdown {"shutdown", this};
  // reaction views
  
  
  // reactions
  void r0_body() { __lf_inner.r0_body(startup, ready); }
  reactor::Reaction r0{"reaction_1", 1, this, [this]() { r0_body(); }}; 
  void r1_body() { __lf_inner.r1_body(ia); }
  reactor::Reaction r1{"reaction_2", 2, this, [this]() { r1_body(); }}; 

 public:
  // input ports
  reactor::Input<double> ia{"ia", this};
  reactor::Input<double> ib{"ib", this};
  // output ports
  
  receiver(const std::string& name, reactor::Environment* __lf_environment, Parameters&& __lf_parameters);
  receiver(const std::string& name, reactor::Reactor* __lf_container, Parameters&& __lf_parameters);

  void assemble() override;
 
 private:
  // connections 
  
};

        
